---
title: "sentiment analysis"
author: "David Bignotti"
date: "December 8, 2017"
output: html_document
---

```{r load libraries}
library("rmongodb")
library("dplyr")
library("randomForest")
library("plyr")
library("class")
library("e1071")
library("nnet")
library("neuralnet")
library("ranger")
```


```{r step 1 tokenization}

tokenize <- function(documents){
  # lowercase words for convenience
  doc <- tolower(documents)
  
  # remove #hashtags and @mentions
  doc <- gsub("(?:#|@)[a-zA-Z0-9_]+ ?", "", doc)
  
  # remove words with >3 numbers (they overwhelm the corpus and are uninformative)
  doc <- gsub("[a-zA-Z]*([0-9]{3,})[a-zA-Z0-9]* ?", "", doc)
  
  # remove punctuation
  doc <- gsub("[[:punct:]]", "", doc)
  
  # remove newline characters
  doc <- gsub("[\r\n]", "", doc)
  
  # regex pattern for removing stop words
  stop_pattern <- paste0("\\b(", paste0(stopwords("en"), collapse="|"), ")\\b")
  doc <- gsub(stop_pattern, "", doc)
  
  # replace whitespace >1 space with a single space
  doc <- gsub(" {2,}", " ", doc)
  
  # split on spaces and return list of character vectors
  doc_words <- strsplit(doc, " ")
  return(doc_words)
}

```


```{r step 2 building the corpus}

corpus_freq <- function(tokens, corpus_size=NULL, word_list = NULL){
  # concatenate tokenized words into a single character list
  all_words <- do.call(c, tokens)
  
  # if corpus size is not blank and word list is, create a word frequency frame
  # take top occuring words up to length of corpus_size and reorder alphabetically
  
  # this gives us an data frame of the most frequent words in our corpus, ordered alphabetically
  # sized by the corpus_size parameter
  if(is.null(word_list) & !is.null(corpus_size)){
    corpusfreq <- data.frame(table(all_words))
    names(corpusfreq) <- c("Word", "Freq")
    corpusfreq$Word <- as.character(corpusfreq$Word)
    corpusfreq$Freq <- as.numeric(corpusfreq$Freq)
    corpusfreq <- corpusfreq[order(-corpusfreq$Freq), ]
    corpusfreq <- corpusfreq[1:corpus_size, ]
    corpusfreq <- corpusfreq[order(corpusfreq$Word), ]
  }
  
  # else it is assumed a pre-compiled word list has been passed into the function
  corpusfreq <- data.frame(word_list)
  names(corpusfreq) <- c("Word")
  
  # N docs is where we will store the document frequency (i.e how many documents a word appears in)
  # we'll need this to calculate TF-IDF
  corpusfreq$n_docs <- 0
  
  # for every vector of words in our tokenized list, count how many times each word in our corpus occurs
  for(token_list in tokens){
    t <- data.frame(table(token_list))
    names(t) <- c("Word", "n_docs")
    t$n_docs <- 1
    t_freq <- merge(x=corpusfreq, y=t, by="Word", all.x=TRUE)
    t_freq$n_docs.y[is.na(t_freq$n_docs.y)] <- 0
    corpusfreq$n_docs <- corpusfreq$n_docs + t_freq$n_docs.y
  }
  return(corpusfreq)
}

```


```{r step 3 term frequency}

tfidf <- function(document, corpus){
  # create a data frame out of a single document and its word frequency
  # for tweets this will be mostly 1s
  doc_f <- data.frame(unlist(table(document)))
  names(doc_f) <- c("Word", "Freq")
  
  # get a data frame of the words in the corpus found in the current document
  in_doc <- intersect(doc_f$Word, corpus$Word)
  doc_f <- doc_f[doc_f$Word %in% in_doc, ]
  
  # get a data frame of the words in the corpus not found in the current document
  # set their frequency to 0
  not_in_doc <- data.frame(Word=setdiff(corpus$Word, document))
  not_in_doc$Freq <-0
  
  # bind  two data frames, we now have frequencies for words that are in our corpus and 0s everywhere else
  tf <- rbind(doc_f, not_in_doc)
  tf$Word <- as.character(tf$Word)
  tf$Freq <- as.numeric(tf$Freq)
  
  # order alphabetically again so it remains compatible with our corpus data frame
  tf <- tf[order(tf$Word), ]
  
  # calculate the tfidf
  # log1p is the same as log(1+___)
  log_freq <- log1p(tf$Freq)
  log_doc_freq <- log1p(nrow(corpus)/corpus$n_docs)
  tf$tfidf <- log_freq * log_doc_freq
  
  # divide by zero errors get NA values, but should be 0s
  tf$tfidf[is.na(tf$tfidf)] <- 0
  return(tf)
}

```


```{r step 4 the feature matrix}

  # this function takes a token_list (output of tokenize) and either a corpus size to create new corpus or a pre-compiled corpus
get_feature_vectors <- function(tokens_list, corpus_size=1500, corpus=NULL){
  if(is.null(corpus)){
    corpus <- corpus_freq(tokens_list, corpus_size=corpus_size)
  }
  
  # our feature matrix starts out as an all 0 matrix with N by C dimensions
  feature_matrix <- matrix(0, length(tokens_list), nrow(corpus))
  
  # for every document in our tokenized list, calculate the tfidf feature vector, and put it into our feature matrix row-wise
  for(i in 1:length(tokens_list)){
    feature_vector <- tfidf(tokens_list[[i]], corpus)$tfidf
    feature_matrix[i, 1:nrow(corpus)] <- feature_vector
  }
  
  # the column names are the same as the alphabetical list of words in our corpus
  # unnecessary step, but useful for examining the resulting feature matrix
  colnames(feature_matrix) <- corpus$Word
  return(data.frame(feature_matrix))
}

```


```{r step 5 helper function for analysis}

  # add_targets takes feature matrix and original data frame (with documents in same order) and adds dependent variable for model trn.
  # in this case it's our pre-labeled sentiment.
add_targets <- function(feature_matrix, df){
  feature_matrix$sentiment <- df$sentiment
  return(feature_matrix)
}


  # ensemble function takes list of prediction vectors, each with length equal to number of documents, and takes majority vote
ensemble <- function(predictions){
  votes <- matrix(0, length(predictions), length(predictions[[1]]))
  for(i in 1:length(predictions)){
    votes[i,] <- ifelse(predictions[[i]] == "P",1,0)
  }
  vote_decision <- colSums(votes)/nrow(votes)
  vote_decision <- ifelse(vote_decision >= .5,"P", "N")
  
  return(vote_decision)
}


  # calculates accuracy, true negative, true positive, and positive predictive value of a confusion matrix.
sensitivity <- function(confusion_matrix){
  acc <- (confusion_matrix[1]+confusion_matrix[4])/sum(confusion_matrix)
  tn <- (confusion_matrix[1]) / (confusion_matrix[3]+confusion_matrix[1])
  ppv <- confusion_matrix[4]/(confusion_matrix[4]+confusion_matrix[3])
  tp <- (confusion_matrix[4]) / (confusion_matrix[4]+confusion_matrix[2])
  return(list(accuracy=acc, specificity=tn, precision=ppv, sensitivity=tp))
}

```


```{r step 6 example}

#Tokenize
tokens <- tokenize(pos_neg_tweets$text)

#Get corpus, and calculate feature vectors
my_features <- get_feature_vectors(tokens, corpus_size=3000)

#Add the dependent variable for model fitting, I.E. the pre-labeled sentiment
my_features <- add_targets(my_features, pos_neg_tweets)
my_features$sentiment <- as.factor(my_features$sentiment)


train <- sample_frac(my_features, .8)
test <- setdiff(my_features, train)
test <- sample_frac(test, 1)


#Formula for each model
form <- as.formula(paste("sentiment~", paste(setdiff(names(test), c("sentiment")), collapse="+")))

# Single hidden-layer neural network of size 10
m_nnet <- nnet(form, data=train, size=10, MaxNWts=100000)
#Naive Bayes algorithm with laplace smoothing
m_nbayes <- naiveBayes(form, data=train, laplace=1000, threshold=.5)
#Random forest
m_randomforest <- ranger(dependent.variable.name="sentiment", data=train, write.forest=TRUE)
#logistic regressions
m_logit <- glm(form, data=train, family=binomial(link='logit'))
#Support vector machine
m_svm <- svm(form, data=train, type="C")


pred_nnet <- predict(m_nnet, test, type="class")

pred_nbayes <- predict(m_nbayes, test, threshold=.5, laplace=1000)

pred_rf <- predict(m_randomforest, data=test)
pred_rf <- pred_rf$predictions

pred_log <- predict(m_logit, test, type="response")
pred_log <- ifelse(pred_log > .5,"P","N")

pred_svm <- predict(m_svm, test)

ens <- ensemble(list(pred_nnet, pred_nbayes, pred_rf, pred_log, pred_svm))


table(test$sentiment, ens)


sensitivity(table(test$sentiment, ens))

```
